-- schema-M4.sql — Vietnamese service partners (M4)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 8 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M4.md, section 7.

-- ORGANISATION: A Vietnamese service company listed in the partner directory. (owner M4; seed file 26_organisation.csv)
CREATE TABLE organisation (
    org_id UUID NOT NULL,
    slug VARCHAR(160),
    org_name VARCHAR(200) NOT NULL,
    legal_form VARCHAR(60) NOT NULL,
    founded_year INTEGER,
    hq_province INTEGER,
    service_groups JSONB NOT NULL,
    provinces JSONB NOT NULL,
    verified_at TIMESTAMPTZ,
    verified_until DATE,
    art13_eligible BOOLEAN NOT NULL,
    org_status VARCHAR(20),
    CONSTRAINT pk_organisation PRIMARY KEY (org_id),
    CONSTRAINT uq_organisation_slug UNIQUE (slug),
    CONSTRAINT ck_organisation_org_status CHECK (org_status IN ('active', 'deactivated')),
    CONSTRAINT fk_organisation_hq_province FOREIGN KEY (hq_province) REFERENCES province (province_id),
    -- M4 BR-004 — a badge ends after it starts
    CONSTRAINT ck_organisation_badge_dates CHECK (verified_until IS NULL OR verified_until > verified_at)
);

-- ORGANISATION_MEMBER_LAYER: The part of a partner profile visible to signed-in members. (owner M4; seed file 27_organisation_member_layer.csv)
CREATE TABLE organisation_member_layer (
    org_id UUID NOT NULL,
    capability_desc_vi TEXT,
    capability_desc_en TEXT,
    portfolio JSONB,
    intl_project_count INTEGER NOT NULL,
    working_languages JSONB,
    CONSTRAINT pk_organisation_member_layer PRIMARY KEY (org_id),
    CONSTRAINT fk_organisation_member_layer_org_id FOREIGN KEY (org_id) REFERENCES organisation (org_id)
);

-- ORGANISATION_PRIVATE_LAYER: The part of a partner profile visible only after an accepted request and NDA. (owner M4; seed file 28_organisation_private_layer.csv)
CREATE TABLE organisation_private_layer (
    org_id UUID NOT NULL,
    rate_card JSONB,
    past_clients JSONB,
    direct_contact VARCHAR(200),
    CONSTRAINT pk_organisation_private_layer PRIMARY KEY (org_id),
    CONSTRAINT fk_organisation_private_layer_org_id FOREIGN KEY (org_id) REFERENCES organisation (org_id)
);

-- VERIFICATION_REQUEST: A partner's application for the VFDA Verified badge and VFDA's decision on it. (owner M4; seed file 29_verification_request.csv)
CREATE TABLE verification_request (
    request_id UUID NOT NULL,
    org_id UUID NOT NULL,
    business_license TEXT NOT NULL,
    reference_projects JSONB NOT NULL,
    status VARCHAR(20),
    decided_by UUID,
    reason TEXT,
    CONSTRAINT pk_verification_request PRIMARY KEY (request_id),
    CONSTRAINT ck_verification_request_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT fk_verification_request_org_id FOREIGN KEY (org_id) REFERENCES organisation (org_id),
    CONSTRAINT fk_verification_request_decided_by FOREIGN KEY (decided_by) REFERENCES user_account (user_id)
);

-- COLLAB_REQUEST: A producer's request to a partner to work on one project, followed to confirmation. (owner M4; seed file 30_collab_request.csv)
CREATE TABLE collab_request (
    request_id UUID NOT NULL,
    project_id UUID NOT NULL,
    org_id UUID NOT NULL,
    services JSONB NOT NULL,
    note TEXT,
    status VARCHAR(20),
    response_note TEXT,
    sent_at TIMESTAMPTZ NOT NULL,
    responded_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT pk_collab_request PRIMARY KEY (request_id),
    CONSTRAINT ck_collab_request_status CHECK (status IN ('pending', 'under_review', 'info_requested', 'accepted', 'declined', 'confirmed', 'withdrawn')),
    CONSTRAINT fk_collab_request_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_collab_request_org_id FOREIGN KEY (org_id) REFERENCES organisation (org_id),
    -- M4 BR-005 — only a confirmed request has a confirmation time
    CONSTRAINT ck_collab_request_confirmed_at CHECK ((status = 'confirmed') = (confirmed_at IS NOT NULL))
);

-- COLLAB_MESSAGE: A message written inside a collaboration request, including every response note; never edited once sent. (owner M4; seed file 31_collab_message.csv)
CREATE TABLE collab_message (
    message_id UUID NOT NULL,
    request_id UUID NOT NULL,
    author_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    body TEXT,
    CONSTRAINT pk_collab_message PRIMARY KEY (message_id),
    CONSTRAINT fk_collab_message_request_id FOREIGN KEY (request_id) REFERENCES collab_request (request_id),
    CONSTRAINT fk_collab_message_author_id FOREIGN KEY (author_id) REFERENCES user_account (user_id)
);

-- NDA_ACCEPTANCE: One party's acceptance of a given NDA version for one collaboration request. (owner M4; seed file 32_nda_acceptance.csv)
CREATE TABLE nda_acceptance (
    nda_acceptance_id UUID NOT NULL,
    request_id UUID NOT NULL,
    party VARCHAR(20) NOT NULL,
    nda_version VARCHAR(20) NOT NULL,
    accepted BOOLEAN NOT NULL,
    accepted_at TIMESTAMPTZ,
    CONSTRAINT pk_nda_acceptance PRIMARY KEY (nda_acceptance_id),
    CONSTRAINT ck_nda_acceptance_party CHECK (party IN ('producer', 'partner')),
    CONSTRAINT fk_nda_acceptance_request_id FOREIGN KEY (request_id) REFERENCES collab_request (request_id)
);

-- DOCUMENT_ACCESS_LOG: A record that one person viewed one shared document at one time. (owner M4; seed file 36_document_access_log.csv)
CREATE TABLE document_access_log (
    access_log_id UUID NOT NULL,
    document_id UUID NOT NULL,
    viewer_id UUID NOT NULL,
    viewed_at TIMESTAMPTZ,
    CONSTRAINT pk_document_access_log PRIMARY KEY (access_log_id),
    CONSTRAINT fk_document_access_log_document_id FOREIGN KEY (document_id) REFERENCES document (document_id),
    CONSTRAINT fk_document_access_log_viewer_id FOREIGN KEY (viewer_id) REFERENCES user_account (user_id)
);
