-- schema-M2.sql — Content pre-check and Article 13 dossier check (M2)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 6 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M2.md, section 7.

-- RULE_SET_VERSION: A numbered edition of the active rule set, created each time a rule is activated. (owner M2; seed file 15_rule_set_version.csv)
CREATE TABLE rule_set_version (
    rule_version VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    CONSTRAINT pk_rule_set_version PRIMARY KEY (rule_version),
    CONSTRAINT fk_rule_set_version_created_by FOREIGN KEY (created_by) REFERENCES user_account (user_id)
);

-- LEGAL_RULE: A content or dossier rule written and signed by the VFDA Legal Board, with its legal citation. (owner M2; seed file 16_legal_rule.csv)
CREATE TABLE legal_rule (
    rule_id UUID NOT NULL,
    rule_code VARCHAR(40) NOT NULL,
    rule_version VARCHAR(20),
    title_vi VARCHAR(200) NOT NULL,
    title_en VARCHAR(200) NOT NULL,
    description_vi TEXT NOT NULL,
    description_en TEXT NOT NULL,
    guidance_vi TEXT NOT NULL,
    guidance_en TEXT NOT NULL,
    citation VARCHAR(200),
    severity VARCHAR(20) NOT NULL,
    topic VARCHAR(20) NOT NULL,
    rule_slug VARCHAR(120) NOT NULL,
    status VARCHAR(20),
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    is_active BOOLEAN,
    CONSTRAINT pk_legal_rule PRIMARY KEY (rule_id),
    CONSTRAINT uq_legal_rule_rule_code UNIQUE (rule_code),
    CONSTRAINT uq_legal_rule_rule_slug UNIQUE (rule_slug),
    CONSTRAINT ck_legal_rule_severity CHECK (severity IN ('notice', 'action')),
    CONSTRAINT ck_legal_rule_topic CHECK (topic IN ('security', 'history', 'religion', 'privacy', 'dossier', 'public_order', 'heritage')),
    CONSTRAINT ck_legal_rule_status CHECK (status IN ('draft', 'approved', 'retired')),
    CONSTRAINT fk_legal_rule_rule_version FOREIGN KEY (rule_version) REFERENCES rule_set_version (rule_version),
    CONSTRAINT fk_legal_rule_approved_by FOREIGN KEY (approved_by) REFERENCES user_account (user_id),
    -- M2 BR-002 — active only with a citation and an approver
    CONSTRAINT ck_legal_rule_approved_needs_signature CHECK (status <> 'approved' OR (citation IS NOT NULL AND approved_by IS NOT NULL)),
    -- 04 minimality — upkeep rule of is_active
    CONSTRAINT ck_legal_rule_active_matches_status CHECK ((CAST(is_active AS TEXT) = 'true') = (status = 'approved'))
);

-- PRECHECK_RUN: One 200-word content pre-check, kept as a demand data point. (owner M2; seed file 17_precheck_run.csv)
CREATE TABLE precheck_run (
    brief_id UUID NOT NULL,
    project_id UUID,
    rule_version VARCHAR(20),
    synopsis_hash TEXT NOT NULL,
    lang VARCHAR(20) NOT NULL,
    flags JSONB,
    country_guess VARCHAR(2),
    attention_level VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_precheck_run PRIMARY KEY (brief_id),
    CONSTRAINT ck_precheck_run_lang CHECK (lang IN ('en', 'vi')),
    CONSTRAINT ck_precheck_run_attention_level CHECK (attention_level IN ('low', 'medium', 'high')),
    CONSTRAINT fk_precheck_run_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_precheck_run_rule_version FOREIGN KEY (rule_version) REFERENCES rule_set_version (rule_version)
);

-- PRECHECK_FINDING: One passage of a pre-checked summary that matches an approved rule. (owner M2; seed file 18_precheck_finding.csv)
CREATE TABLE precheck_finding (
    brief_id UUID NOT NULL,
    rule_code VARCHAR(40) NOT NULL,
    span_start INTEGER NOT NULL,
    span_end INTEGER NOT NULL,
    quoted_text TEXT,
    explanation_vi TEXT,
    explanation_en TEXT,
    CONSTRAINT pk_precheck_finding PRIMARY KEY (brief_id, rule_code, span_start),
    CONSTRAINT fk_precheck_finding_brief_id FOREIGN KEY (brief_id) REFERENCES precheck_run (brief_id),
    CONSTRAINT fk_precheck_finding_rule_code FOREIGN KEY (rule_code) REFERENCES legal_rule (rule_code),
    -- M2 §6.1 — the span is the quoted passage
    CONSTRAINT ck_precheck_finding_span_matches_quote CHECK (span_end - span_start = LENGTH(quoted_text))
);

-- COMPLIANCE_RUN: One content check of a project against the active rule set. (owner M2; seed file 19_compliance_run.csv)
CREATE TABLE compliance_run (
    run_id UUID NOT NULL,
    project_id UUID NOT NULL,
    rule_version VARCHAR(20),
    run_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_compliance_run PRIMARY KEY (run_id),
    CONSTRAINT fk_compliance_run_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_compliance_run_rule_version FOREIGN KEY (rule_version) REFERENCES rule_set_version (rule_version)
);

-- COMPLIANCE_FINDING: One finding of a project content check that a member can mark as reviewed. (owner M2; seed file 20_compliance_finding.csv)
CREATE TABLE compliance_finding (
    finding_id UUID NOT NULL,
    run_id UUID NOT NULL,
    rule_code VARCHAR(40),
    quoted_text TEXT,
    finding_status VARCHAR(20),
    reviewer_note TEXT,
    CONSTRAINT pk_compliance_finding PRIMARY KEY (finding_id),
    CONSTRAINT ck_compliance_finding_finding_status CHECK (finding_status IN ('open', 'reviewed')),
    CONSTRAINT fk_compliance_finding_run_id FOREIGN KEY (run_id) REFERENCES compliance_run (run_id),
    CONSTRAINT fk_compliance_finding_rule_code FOREIGN KEY (rule_code) REFERENCES legal_rule (rule_code)
);
