-- schema-M7.sql — VFDA support (M7)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 3 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M7.md, section 7.

-- LOCATION_INTEREST: A member's statement that a project is interested in a location. (owner M7; seed file 41_location_interest.csv)
CREATE TABLE location_interest (
    interest_id UUID NOT NULL,
    project_id UUID NOT NULL,
    location_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_location_interest PRIMARY KEY (interest_id),
    CONSTRAINT fk_location_interest_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_location_interest_location_id FOREIGN KEY (location_id) REFERENCES location (location_id)
);

-- PROVINCE_NOTICE: The notice VFDA sends a province about a project's interest, and the province's reply. (owner M7; seed file 42_province_notice.csv)
CREATE TABLE province_notice (
    interest_id UUID NOT NULL,
    province_id INTEGER NOT NULL,
    project_summary TEXT NOT NULL,
    authority_email VARCHAR(254) NOT NULL,
    drafted_at TIMESTAMPTZ NOT NULL,
    reviewed_by UUID,
    sent_at TIMESTAMPTZ,
    delivery_status VARCHAR(20),
    received_at TIMESTAMPTZ,
    response VARCHAR(20),
    note TEXT,
    responded_at TIMESTAMPTZ,
    CONSTRAINT pk_province_notice PRIMARY KEY (interest_id),
    CONSTRAINT ck_province_notice_delivery_status CHECK (delivery_status IN ('queued', 'sent', 'bounced')),
    CONSTRAINT ck_province_notice_response CHECK (response IN ('received', 'info_needed', 'cannot_support')),
    CONSTRAINT fk_province_notice_interest_id FOREIGN KEY (interest_id) REFERENCES location_interest (interest_id),
    CONSTRAINT fk_province_notice_province_id FOREIGN KEY (province_id) REFERENCES province (province_id),
    CONSTRAINT fk_province_notice_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES user_account (user_id)
);

-- CONSULTATION_BOOKING: A member's booked consultation slot with a VFDA officer. (owner M7; seed file 43_consultation_booking.csv)
CREATE TABLE consultation_booking (
    booking_id UUID NOT NULL,
    member_id UUID NOT NULL,
    topic VARCHAR(20) NOT NULL,
    slot_start TIMESTAMPTZ NOT NULL,
    timezone VARCHAR(40) NOT NULL,
    officer_id UUID,
    booking_status VARCHAR(20),
    CONSTRAINT pk_consultation_booking PRIMARY KEY (booking_id),
    CONSTRAINT ck_consultation_booking_topic CHECK (topic IN ('dossier', 'locations', 'partners', 'provincial_notice', 'general')),
    CONSTRAINT ck_consultation_booking_booking_status CHECK (booking_status IN ('confirmed', 'rescheduled')),
    CONSTRAINT fk_consultation_booking_member_id FOREIGN KEY (member_id) REFERENCES user_account (user_id),
    CONSTRAINT fk_consultation_booking_officer_id FOREIGN KEY (officer_id) REFERENCES user_account (user_id)
);
