-- schema-SYS.sql — Platform foundation (SYS)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 6 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-SYS.md, section 7.

-- USER_ACCOUNT: A person's sign-in identity on CINEMATCH, carrying exactly one of six roles. (owner SYS; seed file 01_user_account.csv)
CREATE TABLE user_account (
    user_id UUID NOT NULL,
    email VARCHAR(254) NOT NULL,
    email_verified BOOLEAN,
    role VARCHAR(20) NOT NULL,
    account_status VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_user_account PRIMARY KEY (user_id),
    CONSTRAINT uq_user_account_email UNIQUE (email),
    CONSTRAINT ck_user_account_role CHECK (role IN ('guest', 'member', 'partner', 'vfda_staff', 'vfda_legal', 'admin')),
    CONSTRAINT ck_user_account_account_status CHECK (account_status IN ('active', 'deactivated'))
);

-- PRODUCER_ORGANISATION: The production company a producer signs up on behalf of. (owner SYS; seed file 02_producer_organisation.csv)
CREATE TABLE producer_organisation (
    producer_org_id UUID NOT NULL,
    org_name VARCHAR(200) NOT NULL,
    country CHAR(2) NOT NULL,
    website VARCHAR(300),
    CONSTRAINT pk_producer_organisation PRIMARY KEY (producer_org_id)
);

-- PROFILE: The personal details shown for an account: name, crew role and preferred language. (owner SYS; seed file 03_profile.csv)
CREATE TABLE profile (
    user_id UUID NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    crew_role VARCHAR(22) NOT NULL,
    locale VARCHAR(20) NOT NULL,
    producer_org_id UUID,
    CONSTRAINT pk_profile PRIMARY KEY (user_id),
    CONSTRAINT ck_profile_crew_role CHECK (crew_role IN ('producer', 'director', 'production_coordinator', 'line_producer', 'other')),
    CONSTRAINT ck_profile_locale CHECK (locale IN ('vi', 'en')),
    CONSTRAINT fk_profile_user_id FOREIGN KEY (user_id) REFERENCES user_account (user_id),
    CONSTRAINT fk_profile_producer_org_id FOREIGN KEY (producer_org_id) REFERENCES producer_organisation (producer_org_id)
);

-- CONSENT: A record that an account accepted a given version of the terms at a given time. (owner SYS; seed file 04_consent.csv)
CREATE TABLE consent (
    user_id UUID NOT NULL,
    consent_version VARCHAR(20) NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_consent PRIMARY KEY (user_id, consent_version),
    CONSTRAINT fk_consent_user_id FOREIGN KEY (user_id) REFERENCES user_account (user_id)
);

-- NOTIFICATION: An in-app message addressed to one account about one event. (owner SYS; seed file 05_notification.csv)
CREATE TABLE notification (
    notification_id UUID NOT NULL,
    recipient_id UUID NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    CONSTRAINT pk_notification PRIMARY KEY (notification_id),
    CONSTRAINT fk_notification_recipient_id FOREIGN KEY (recipient_id) REFERENCES user_account (user_id)
);

-- EMAIL_DELIVERY: One transactional email handed to the email provider, with its delivery outcome. (owner SYS; seed file 06_email_delivery.csv)
CREATE TABLE email_delivery (
    email_delivery_id UUID NOT NULL,
    notification_id UUID,
    template_id VARCHAR(60) NOT NULL,
    recipient_email VARCHAR(254) NOT NULL,
    variables JSONB NOT NULL,
    delivery_status VARCHAR(20),
    provider_message_id TEXT,
    CONSTRAINT pk_email_delivery PRIMARY KEY (email_delivery_id),
    CONSTRAINT uq_email_delivery_provider_message_id UNIQUE (provider_message_id),
    CONSTRAINT ck_email_delivery_delivery_status CHECK (delivery_status IN ('queued', 'sent', 'bounced')),
    CONSTRAINT fk_email_delivery_notification_id FOREIGN KEY (notification_id) REFERENCES notification (notification_id)
);
