-- schema-M1.sql — Segment router (M1)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 3 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M1.md, section 7.

-- SEGMENT_RULE: One row of the VFDA-approved decision table that maps router answers to segment A, B or C. (owner M1; seed file 07_segment_rule.csv)
CREATE TABLE segment_rule (
    segment_rule_id UUID NOT NULL,
    q1_shoot_in_vn BOOLEAN NOT NULL,
    q2_release VARCHAR(20),
    q3_producer VARCHAR(20),
    result_segment VARCHAR(20),
    version VARCHAR(20) NOT NULL,
    CONSTRAINT pk_segment_rule PRIMARY KEY (segment_rule_id),
    CONSTRAINT ck_segment_rule_q2_release CHECK (q2_release IN ('abroad', 'vietnam', 'both')),
    CONSTRAINT ck_segment_rule_q3_producer CHECK (q3_producer IN ('foreign', 'vietnamese', 'coproduction')),
    CONSTRAINT ck_segment_rule_result_segment CHECK (result_segment IN ('A', 'B', 'C'))
);

-- SEGMENT_REQUIREMENT: One item a segment needs or does not need, used to configure the journey and the gauges. (owner M1; seed file 08_segment_requirement.csv)
CREATE TABLE segment_requirement (
    segment VARCHAR(20) NOT NULL,
    requirement_code VARCHAR(40) NOT NULL,
    label_vi TEXT NOT NULL,
    label_en TEXT NOT NULL,
    needed BOOLEAN NOT NULL,
    CONSTRAINT pk_segment_requirement PRIMARY KEY (segment, requirement_code),
    CONSTRAINT ck_segment_requirement_segment CHECK (segment IN ('A', 'B', 'C'))
);

-- SEGMENT_DECISION: The segment given to a visitor or project from their answers, including any manual override. (owner M1; seed file 10_segment_decision.csv)
CREATE TABLE segment_decision (
    segment_decision_id UUID NOT NULL,
    project_id UUID,
    session_key VARCHAR(40),
    segment_rule_id UUID,
    q1_shoot_in_vn BOOLEAN NOT NULL,
    q2_release VARCHAR(20),
    q3_producer VARCHAR(20),
    q4_needs JSONB,
    segment VARCHAR(20),
    segment_override VARCHAR(20),
    decided_by JSONB,
    journey_config JSONB,
    CONSTRAINT pk_segment_decision PRIMARY KEY (segment_decision_id),
    CONSTRAINT ck_segment_decision_q2_release CHECK (q2_release IN ('abroad', 'vietnam', 'both')),
    CONSTRAINT ck_segment_decision_q3_producer CHECK (q3_producer IN ('foreign', 'vietnamese', 'coproduction')),
    CONSTRAINT ck_segment_decision_segment CHECK (segment IN ('A', 'B', 'C')),
    CONSTRAINT ck_segment_decision_segment_override CHECK (segment_override IN ('A', 'B', 'C')),
    CONSTRAINT fk_segment_decision_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_segment_decision_segment_rule_id FOREIGN KEY (segment_rule_id) REFERENCES segment_rule (segment_rule_id),
    -- M1 §6.1 — a decision belongs to a saved project or to an anonymous session, never both
    CONSTRAINT ck_segment_decision_one_owner CHECK ((project_id IS NULL) <> (session_key IS NULL))
);
