-- schema-M3.sql — Location discovery (M3)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 6 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M3.md, section 7.

-- PROVINCE: One of the 34 provincial-level units after the 2025 reorganisation. (owner M3; seed file 12_province.csv)
CREATE TABLE province (
    province_id INTEGER NOT NULL,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    region VARCHAR(20),
    merged_from JSONB,
    CONSTRAINT pk_province PRIMARY KEY (province_id),
    CONSTRAINT uq_province_name UNIQUE (name),
    CONSTRAINT uq_province_slug UNIQUE (slug),
    CONSTRAINT ck_province_region CHECK (region IN ('north', 'central', 'south'))
);

-- LOCATION: A filming location in Vietnam described and published by VFDA staff. (owner M3; seed file 21_location.csv)
CREATE TABLE location (
    location_id UUID NOT NULL,
    slug VARCHAR(160),
    province_id INTEGER NOT NULL,
    name_vi VARCHAR(200) NOT NULL,
    name_en VARCHAR(200) NOT NULL,
    district VARCHAR(120),
    lat NUMERIC(9,6) NOT NULL,
    lng NUMERIC(9,6) NOT NULL,
    airport_km INTEGER,
    scene_types JSONB NOT NULL,
    desc_vi TEXT NOT NULL,
    desc_en TEXT NOT NULL,
    crew_capacity VARCHAR(20) NOT NULL,
    lodging_20km BOOLEAN NOT NULL,
    grid_power BOOLEAN NOT NULL,
    truck_access BOOLEAN NOT NULL,
    months_to_avoid JSONB,
    permit_complexity VARCHAR(20) NOT NULL,
    restriction_note TEXT,
    availability VARCHAR(20) NOT NULL,
    intake_status VARCHAR(20),
    published BOOLEAN,
    blocked_reason TEXT,
    CONSTRAINT pk_location PRIMARY KEY (location_id),
    CONSTRAINT uq_location_slug UNIQUE (slug),
    CONSTRAINT ck_location_crew_capacity CHECK (crew_capacity IN ('u15', '15_50', 'o50')),
    CONSTRAINT ck_location_permit_complexity CHECK (permit_complexity IN ('low', 'medium', 'high')),
    CONSTRAINT ck_location_availability CHECK (availability IN ('open', 'survey_in_progress', 'paused')),
    CONSTRAINT ck_location_intake_status CHECK (intake_status IN ('awaiting_contact', 'published', 'unpublished')),
    CONSTRAINT fk_location_province_id FOREIGN KEY (province_id) REFERENCES province (province_id),
    -- M3 BR-004, BR-008 — published only in the published state
    CONSTRAINT ck_location_published_matches_status CHECK ((CAST(published AS TEXT) = 'true') = (intake_status = 'published')),
    -- M3 §5.1 FR-002 — coordinates inside Vietnam
    CONSTRAINT ck_location_in_vietnam CHECK (lat BETWEEN 8 AND 24 AND lng BETWEEN 102 AND 110)
);

-- LOCATION_IMAGE: A photo of a location with its source and usage right. (owner M3; seed file 22_location_image.csv)
CREATE TABLE location_image (
    image_url TEXT NOT NULL,
    location_id UUID NOT NULL,
    image_source TEXT NOT NULL,
    usage_right TEXT NOT NULL,
    status VARCHAR(20),
    CONSTRAINT pk_location_image PRIMARY KEY (image_url),
    CONSTRAINT ck_location_image_status CHECK (status IN ('pending', 'approved', 'hidden')),
    CONSTRAINT fk_location_image_location_id FOREIGN KEY (location_id) REFERENCES location (location_id)
);

-- AUTHORITY_CONTACT: The local authority office and person to contact about filming at a location, verified by VFDA. (owner M3; seed file 23_authority_contact.csv)
CREATE TABLE authority_contact (
    location_id UUID NOT NULL,
    authority_name VARCHAR(200) NOT NULL,
    contact_name VARCHAR(120) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    contact_email VARCHAR(254),
    verified_by UUID NOT NULL,
    verified_at TIMESTAMPTZ,
    contact_verified BOOLEAN,
    CONSTRAINT pk_authority_contact PRIMARY KEY (location_id),
    CONSTRAINT fk_authority_contact_location_id FOREIGN KEY (location_id) REFERENCES location (location_id),
    CONSTRAINT fk_authority_contact_verified_by FOREIGN KEY (verified_by) REFERENCES user_account (user_id)
);

-- LOCATION_QUERY: A scene description a user typed and the attributes extracted from it, stored without personal data. (owner M3; seed file 24_location_query.csv)
CREATE TABLE location_query (
    query_id UUID NOT NULL,
    project_id UUID,
    scene_description TEXT NOT NULL,
    shoot_month INTEGER,
    attributes JSONB,
    CONSTRAINT pk_location_query PRIMARY KEY (query_id),
    CONSTRAINT fk_location_query_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    -- M3 §5.1 FR-010 — 10 to 1000 characters
    CONSTRAINT ck_location_query_length CHECK (LENGTH(scene_description) BETWEEN 10 AND 1000)
);

-- PROJECT_SHORTLIST: A location a project has kept as its primary or backup choice. (owner M3; seed file 25_project_shortlist.csv)
CREATE TABLE project_shortlist (
    shortlist_id UUID NOT NULL,
    project_id UUID NOT NULL,
    location_id UUID NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT pk_project_shortlist PRIMARY KEY (shortlist_id),
    CONSTRAINT ck_project_shortlist_role CHECK (role IN ('primary', 'backup')),
    CONSTRAINT fk_project_shortlist_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_project_shortlist_location_id FOREIGN KEY (location_id) REFERENCES location (location_id)
);
