-- schema-M5.sql — Dossier kit, bilingual drafts and countdown (M5)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 7 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M5.md, section 7.

-- DOCUMENT_TYPE: A kind of dossier document, with its legal basis and template. (owner M5; seed file 33_document_type.csv)
CREATE TABLE document_type (
    doc_code VARCHAR(40) NOT NULL,
    name_vi TEXT,
    name_en TEXT,
    basis VARCHAR(20),
    template_url TEXT,
    segments JSONB NOT NULL,
    CONSTRAINT pk_document_type PRIMARY KEY (doc_code),
    CONSTRAINT ck_document_type_basis CHECK (basis IN ('law', 'common', 'location'))
);

-- DOCUMENT_SLOT: The place for one document type in one project, with its status. (owner M5; seed file 34_document_slot.csv)
CREATE TABLE document_slot (
    project_id UUID NOT NULL,
    doc_code VARCHAR(40) NOT NULL,
    state VARCHAR(20),
    CONSTRAINT pk_document_slot PRIMARY KEY (project_id, doc_code),
    CONSTRAINT ck_document_slot_state CHECK (state IN ('present', 'needs_fix', 'pending', 'missing')),
    CONSTRAINT fk_document_slot_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_document_slot_doc_code FOREIGN KEY (doc_code) REFERENCES document_type (doc_code)
);

-- DOCUMENT: One uploaded file version in a project's document slot. (owner M5; seed file 35_document.csv)
CREATE TABLE document (
    document_id UUID NOT NULL,
    project_id UUID NOT NULL,
    doc_code VARCHAR(40) NOT NULL,
    file_path TEXT NOT NULL,
    version INTEGER NOT NULL,
    uploaded_by UUID NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_document PRIMARY KEY (document_id),
    CONSTRAINT fk_document_project_id_doc_code FOREIGN KEY (project_id, doc_code) REFERENCES document_slot (project_id, doc_code),
    CONSTRAINT fk_document_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES user_account (user_id),
    -- M5 §6.1 — versions count from 1
    CONSTRAINT ck_document_version_positive CHECK (version >= 1)
);

-- BILINGUAL_DOCUMENT: A generated English–Vietnamese draft of one document of a project. (owner M5; seed file 37_bilingual_document.csv)
CREATE TABLE bilingual_document (
    project_id UUID NOT NULL,
    doc_code VARCHAR(40) NOT NULL,
    structure_version VARCHAR(20),
    synopsis_en TEXT NOT NULL,
    project_meta JSONB NOT NULL,
    pdf_url TEXT,
    CONSTRAINT pk_bilingual_document PRIMARY KEY (project_id, doc_code),
    CONSTRAINT fk_bilingual_document_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_bilingual_document_doc_code FOREIGN KEY (doc_code) REFERENCES document_type (doc_code)
);

-- BILINGUAL_PARAGRAPH: One aligned source/Vietnamese paragraph pair of a bilingual draft, with its proofreading status. (owner M5; seed file 38_bilingual_paragraph.csv)
CREATE TABLE bilingual_paragraph (
    project_id UUID NOT NULL,
    doc_code VARCHAR(40) NOT NULL,
    idx INTEGER NOT NULL,
    source_text TEXT,
    target_text TEXT,
    status VARCHAR(20),
    reviewed_by UUID,
    reviewer_org_id UUID,
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT pk_bilingual_paragraph PRIMARY KEY (project_id, doc_code, idx),
    CONSTRAINT ck_bilingual_paragraph_status CHECK (status IN ('machine', 'reviewed')),
    CONSTRAINT fk_bilingual_paragraph_project_id_doc_code FOREIGN KEY (project_id, doc_code) REFERENCES bilingual_document (project_id, doc_code),
    CONSTRAINT fk_bilingual_paragraph_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES user_account (user_id),
    CONSTRAINT fk_bilingual_paragraph_reviewer_org_id FOREIGN KEY (reviewer_org_id) REFERENCES organisation (org_id),
    -- M5 BR-002, FR-006 — a proofread paragraph names its proofreader
    CONSTRAINT ck_bilingual_paragraph_reviewer CHECK (status <> 'reviewed' OR reviewed_by IS NOT NULL)
);

-- PROJECT_GLOSSARY: A project's agreed translation of one term, applied to every later draft of that project. (owner M5; seed file 39_project_glossary.csv)
CREATE TABLE project_glossary (
    project_id UUID NOT NULL,
    term_en VARCHAR(120) NOT NULL,
    term_vi VARCHAR(120),
    CONSTRAINT pk_project_glossary PRIMARY KEY (project_id, term_en),
    CONSTRAINT fk_project_glossary_project_id FOREIGN KEY (project_id) REFERENCES project (project_id)
);

-- PUBLIC_HOLIDAY: A public holiday period shown on the licensing timeline, official or expected. (owner M5; seed file 40_public_holiday.csv)
CREATE TABLE public_holiday (
    name VARCHAR(120) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_expected BOOLEAN NOT NULL,
    CONSTRAINT pk_public_holiday PRIMARY KEY (name, start_date),
    -- M5 §6.1 — a holiday ends on or after its first day
    CONSTRAINT ck_public_holiday_dates CHECK (end_date >= start_date)
);
