-- schema-M10.sql — VFDA back office (M10)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 3 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M10.md, section 7.

-- MODERATION_ITEM: A partner's published content (profile text or location photo) waiting for, or carrying, VFDA staff's approve-or-hide decision. (owner M10; seed file 44_moderation_item.csv)
CREATE TABLE moderation_item (
    content_id UUID NOT NULL,
    content_type VARCHAR(20),
    organisation_id UUID,
    location_image_id TEXT,
    submitted_by UUID,
    submitted_at TIMESTAMPTZ,
    content_status VARCHAR(20),
    reason TEXT,
    decided_by UUID,
    decided_at TIMESTAMPTZ,
    CONSTRAINT pk_moderation_item PRIMARY KEY (content_id),
    CONSTRAINT ck_moderation_item_content_type CHECK (content_type IN ('org_profile', 'location_image', 'showcase')),
    CONSTRAINT ck_moderation_item_content_status CHECK (content_status IN ('pending', 'approved', 'hidden')),
    CONSTRAINT fk_moderation_item_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation (org_id),
    CONSTRAINT fk_moderation_item_location_image_id FOREIGN KEY (location_image_id) REFERENCES location_image (image_url),
    CONSTRAINT fk_moderation_item_submitted_by FOREIGN KEY (submitted_by) REFERENCES user_account (user_id),
    CONSTRAINT fk_moderation_item_decided_by FOREIGN KEY (decided_by) REFERENCES user_account (user_id),
    -- M10 §6 — exactly one target (04 Structural findings)
    CONSTRAINT ck_moderation_item_one_target CHECK ((organisation_id IS NULL) <> (location_image_id IS NULL)),
    -- M10 §5.1 FR-001 — the target matches the content type
    CONSTRAINT ck_moderation_item_target_matches_type CHECK ((content_type = 'org_profile' AND organisation_id IS NOT NULL) OR (content_type = 'location_image' AND location_image_id IS NOT NULL) OR content_type = 'showcase'),
    -- M10 BR-002 — hiding needs a reason
    CONSTRAINT ck_moderation_item_hidden_needs_reason CHECK (content_status <> 'hidden' OR reason IS NOT NULL)
);

-- AUDIT_LOG: A permanent record of one administrative action: who did what to which record, and when. (owner M10; seed file 45_audit_log.csv)
CREATE TABLE audit_log (
    audit_log_id UUID NOT NULL,
    action VARCHAR(60) NOT NULL,
    admin_id UUID NOT NULL,
    target_id UUID,
    logged_at TIMESTAMPTZ,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_log_id),
    CONSTRAINT fk_audit_log_admin_id FOREIGN KEY (admin_id) REFERENCES user_account (user_id)
);

-- QUARTERLY_REPORT: A quarterly demand report with its bilingual commentary, reread by a staff member before it is exported. (owner M10; seed file 46_quarterly_report.csv)
CREATE TABLE quarterly_report (
    report_id UUID NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    demand_index JSONB NOT NULL,
    narrative_vi TEXT NOT NULL,
    narrative_en TEXT,
    reread_by UUID,
    report_pdf_url TEXT,
    exported_at TIMESTAMPTZ,
    CONSTRAINT pk_quarterly_report PRIMARY KEY (report_id),
    CONSTRAINT fk_quarterly_report_reread_by FOREIGN KEY (reread_by) REFERENCES user_account (user_id),
    -- M10 §5.1 FR-003 — a period
    CONSTRAINT ck_quarterly_report_period CHECK (period_end >= period_start),
    -- M10 BR-004 — no export before a reread
    CONSTRAINT ck_quarterly_report_reread_before_export CHECK (exported_at IS NULL OR reread_by IS NOT NULL)
);
