-- schema-M0.sql — Project workspace and readiness dashboard (M0)
-- Generated by tools/build_schema.py from data/04-data-model.md (logical model) and data/seed/schema.json.
-- Portable SQL: SQLite 3 and PostgreSQL 14+. 4 tables, in load order.
-- Load: run every data/schema/schema-*.sql, then the data/seed/NN_<table>.csv files in filename order
-- (python3 data/schema/load_check.py does both and reports any error).
-- Rules that span tables are not here: see data/data-model-M0.md, section 7.

-- PROJECT: A film or content production a producer is preparing to shoot in Vietnam. (owner M0; seed file 09_project.csv)
CREATE TABLE project (
    project_id UUID NOT NULL,
    producer_org_id UUID NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    format VARCHAR(20) NOT NULL,
    segment VARCHAR(20) NOT NULL,
    shoot_date DATE,
    buffer_days INTEGER NOT NULL,
    shoot_days_vn INTEGER,
    crew_size_band VARCHAR(20),
    logline VARCHAR(500),
    stage VARCHAR(20),
    updated_at TIMESTAMPTZ,
    CONSTRAINT pk_project PRIMARY KEY (project_id),
    CONSTRAINT ck_project_format CHECK (format IN ('feature', 'documentary', 'commercial', 'tv', 'music_video')),
    CONSTRAINT ck_project_segment CHECK (segment IN ('A', 'B', 'C')),
    CONSTRAINT ck_project_crew_size_band CHECK (crew_size_band IN ('u15', '15_50', 'o50')),
    CONSTRAINT ck_project_stage CHECK (stage IN ('draft', 'preparing', 'archived')),
    CONSTRAINT fk_project_producer_org_id FOREIGN KEY (producer_org_id) REFERENCES producer_organisation (producer_org_id),
    -- M2 BR-006 — the safety buffer is a number of days
    CONSTRAINT ck_project_days_not_negative CHECK (buffer_days >= 0 AND (shoot_days_vn IS NULL OR shoot_days_vn >= 0))
);

-- PROJECT_MEMBER: A person's access to one project, with view or edit permission. (owner M0; seed file 11_project_member.csv)
CREATE TABLE project_member (
    member_id UUID NOT NULL,
    project_id UUID NOT NULL,
    user_id UUID,
    invitee_email VARCHAR(254) NOT NULL,
    permission VARCHAR(20) NOT NULL,
    invite_status VARCHAR(20),
    CONSTRAINT pk_project_member PRIMARY KEY (member_id),
    CONSTRAINT ck_project_member_permission CHECK (permission IN ('view', 'edit')),
    CONSTRAINT ck_project_member_invite_status CHECK (invite_status IN ('pending', 'accepted')),
    CONSTRAINT fk_project_member_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_project_member_user_id FOREIGN KEY (user_id) REFERENCES user_account (user_id)
);

-- PROJECT_PROVINCE: A province a project plans to shoot in. (owner M0; seed file 13_project_province.csv)
CREATE TABLE project_province (
    project_id UUID NOT NULL,
    province_id INTEGER NOT NULL,
    CONSTRAINT pk_project_province PRIMARY KEY (project_id, province_id),
    CONSTRAINT fk_project_province_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_project_province_province_id FOREIGN KEY (province_id) REFERENCES province (province_id)
);

-- READINESS_SNAPSHOT: The overall readiness of a project as recorded on one night. (owner M0; seed file 14_readiness_snapshot.csv)
CREATE TABLE readiness_snapshot (
    snapshot_id UUID NOT NULL,
    project_id UUID NOT NULL,
    snapshot_date DATE NOT NULL,
    readiness_total NUMERIC(5,2),
    CONSTRAINT pk_readiness_snapshot PRIMARY KEY (snapshot_id),
    CONSTRAINT fk_readiness_snapshot_project_id FOREIGN KEY (project_id) REFERENCES project (project_id),
    -- M0 §5.1 FR-008 — a percentage
    CONSTRAINT ck_readiness_snapshot_range CHECK (readiness_total BETWEEN 0 AND 100)
);
