# -*- coding: utf-8 -*-
"""Hand-written inputs of data/data-model-<MODULE>.md that the logical model does not hold:
where each business rule is enforced, the boundary rows, the normalization exceptions and the privacy declaration.
Every evidence filter is resolved against the seed files by tools/build_dm_docs.py; a filter that matches no row
stops the build, so this file cannot drift from the data.

Filter values: a plain string matches the CSV cell; ("len", n) length; ("ne", v) not equal; ("lt", v) / ("gt", v)
string compare; ("empty",) / ("nonempty",); "@project:<name>", "@org:<name>", "@loc:<slug>", "@user:<e-mail start>"
resolve to the key of that row."""

# label columns shown for an evidence row
LABEL = {
 "USER_ACCOUNT": ["email", "role", "account_status"], "PROFILE": ["full_name"], "PRODUCER_ORGANISATION": ["org_name"],
 "CONSENT": ["consent_version"], "NOTIFICATION": ["event_type"], "EMAIL_DELIVERY": ["template_id", "delivery_status"],
 "SEGMENT_RULE": ["q2_release", "q3_producer", "result_segment", "version"], "SEGMENT_REQUIREMENT": ["segment", "requirement_code", "needed"],
 "SEGMENT_DECISION": ["session_key", "segment", "segment_override"], "PROJECT": ["project_name", "segment", "stage"],
 "PROJECT_MEMBER": ["invitee_email", "permission", "invite_status"], "PROJECT_PROVINCE": ["province_id"], "PROVINCE": ["name", "region"],
 "READINESS_SNAPSHOT": ["snapshot_date", "readiness_total"], "RULE_SET_VERSION": ["rule_version"],
 "LEGAL_RULE": ["rule_code", "status", "severity"], "PRECHECK_RUN": ["country_guess", "attention_level"],
 "PRECHECK_FINDING": ["rule_code", "quoted_text"], "COMPLIANCE_RUN": ["rule_version", "run_at"],
 "COMPLIANCE_FINDING": ["rule_code", "finding_status"], "LOCATION": ["slug", "intake_status", "availability"],
 "LOCATION_IMAGE": ["image_url", "status"], "AUTHORITY_CONTACT": ["authority_name", "contact_verified", "verified_at"],
 "LOCATION_QUERY": ["scene_description", "shoot_month"], "PROJECT_SHORTLIST": ["role"], "ORGANISATION": ["org_name", "org_status", "verified_until"],
 "ORGANISATION_MEMBER_LAYER": ["intl_project_count"], "ORGANISATION_PRIVATE_LAYER": ["direct_contact"],
 "VERIFICATION_REQUEST": ["status", "reason"], "COLLAB_REQUEST": ["status", "sent_at"], "COLLAB_MESSAGE": ["created_at"],
 "NDA_ACCEPTANCE": ["party", "accepted"], "DOCUMENT_TYPE": ["doc_code", "basis"], "DOCUMENT_SLOT": ["doc_code", "state"],
 "DOCUMENT": ["file_path", "version"], "DOCUMENT_ACCESS_LOG": ["viewed_at"], "BILINGUAL_DOCUMENT": ["doc_code", "pdf_url"],
 "BILINGUAL_PARAGRAPH": ["idx", "status"], "PROJECT_GLOSSARY": ["term_en", "term_vi"], "PUBLIC_HOLIDAY": ["name", "is_expected"],
 "LOCATION_INTEREST": ["created_at"], "PROVINCE_NOTICE": ["delivery_status", "response"],
 "CONSULTATION_BOOKING": ["topic", "booking_status", "timezone"], "MODERATION_ITEM": ["content_type", "content_status"],
 "AUDIT_LOG": ["action", "logged_at"], "QUARTERLY_REPORT": ["period_start", "period_end"],
}

FERRY = "@project:The Last Ferry"
# ---------------------------------------------------------------------------------------------------------------
# Business rules: (where it is enforced, named object(s), evidence rows, what the rows show)
# kinds: SCHEMA (in data/schema now) · SEED CHECK (seed_rules.py, before writing) · TRIGGER / RLS / VIEW / APP (built at the
# Plan step; the named object is the brief for the agent) · NOT DATA (a rule about wording, process or an external service)
E = lambda ent, flt, why: (ent, flt, why)
BR_ENF = {
 "SYS BR-001": ("RLS (Plan step)", "policies `rls_authority_contact_members`, `rls_org_private_after_nda`, `rls_document_project_members`",
                [E("AUTHORITY_CONTACT", {}, "contacts exist for 11 locations; a guest session must read 0 of them (SYS US-2)")]),
 "SYS BR-002": ("SEED CHECK + TRIGGER (Plan step)", "seed_rules: staff, Legal Board, admin and partner profiles have no producer organisation; trigger `trg_role_grant_audit` writes `role.grant`",
                [E("USER_ACCOUNT", {"role": "partner", "email": ("startswith", "lan.pham")}, "a partner account granted by the admin"),
                 E("AUDIT_LOG", {"action": "role.grant"}, "the grant is in the audit log")]),
 "SYS BR-003": ("SCHEMA", "primary key `pk_consent` (user_id, consent_version) + `accepted_at NOT NULL`",
                [E("CONSENT", {"consent_version": "2026.2"}, "Lena Park re-consents to a new terms version: a second row, the first is kept")]),
 "SYS BR-004": ("NOT DATA", "no password, hash or token column exists in any table (Supabase Auth keeps them)",
                [E("USER_ACCOUNT", {}, "USER_ACCOUNT has no password column")]),
 "SYS BR-005": ("SCHEMA + SEED CHECK", "`ck_user_account_account_status`; seed_rules: a deactivated account is anonymised",
                [E("USER_ACCOUNT", {"account_status": "deactivated"}, "deactivated, e-mail anonymised"),
                 E("PROJECT_MEMBER", {"invitee_email": ("startswith", "former-member")}, "its project membership is kept")]),
 "M1 BR-001": ("SCHEMA + SEED CHECK", "`pk_segment_rule`, `ck_segment_rule_result_segment`; seed_rules: a decision without override equals its rule",
                [E("SEGMENT_RULE", {"version": "2026.1", "q2_release": "abroad", "q3_producer": "foreign"}, "abroad + foreign → A"),
                 E("SEGMENT_RULE", {"version": "2025.12"}, "a superseded version is kept, never used")]),
 "M1 BR-002": ("APP (Plan step)", "router function ignores q4_needs when choosing the segment",
                [E("SEGMENT_DECISION", {"session_key": "session:5e0f7b22"}, "q4 = equipment, locations; segment from q1–q3 only")]),
 "M1 BR-003": ("SCHEMA + SEED CHECK", "`ck_segment_decision_segment_override`; seed_rules: an override sets the segment",
                [E("SEGMENT_DECISION", {"segment_override": "B"}, "override A → B is recorded"),
                 E("SEGMENT_DECISION", {"segment_override": "C"}, "override A → C is recorded")]),
 "M1 BR-004": ("SEED CHECK + APP", "segment change writes a new SEGMENT_DECISION; documents are never deleted",
                [E("SEGMENT_DECISION", {"project_id": "@project:Rice and Salt", "segment": "B"}, "Rice and Salt moved from A to B"),
                 E("DOCUMENT_SLOT", {"project_id": "@project:Rice and Salt"}, "its document slots are kept")]),
 "M0 BR-001": ("VIEW (Plan step) + SEED CHECK", "view `v_project_readiness`; seed_rules.readiness() recomputes the latest snapshot",
                [E("READINESS_SNAPSHOT", {"project_id": FERRY, "snapshot_date": "2026-09-27"}, "68.75 = formula of M0 §9 on the seed data")]),
 "M0 BR-002": ("SEED CHECK + VIEW", "seed_rules: no Article 13 slot on a segment C project",
                [E("PROJECT", {"segment": "C"}, "Monsoon Signal (segment C)"),
                 E("DOCUMENT_SLOT", {"doc_code": "SERVICE_CONTRACT_C"}, "its only slot is the segment C contract")]),
 "M0 BR-003": ("VIEW (Plan step)", "`v_project_readiness.next_actions` — one action per gauge",
                [E("PROJECT", {"project_name": "Monsoon Signal"}, "empty project: every gauge 0 % with one first next step")]),
 "M0 BR-004": ("SCHEMA", "table `segment_requirement` (weights and items per segment) read by the view",
                [E("SEGMENT_REQUIREMENT", {"segment": "C", "requirement_code": "ART13_LICENCE"}, "segment C: licence *not needed*")]),
 "M0 BR-005": ("SCHEMA + RLS (Plan step)", "`ck_project_stage` (draft, preparing, archived); policy `rls_project_archived_read_only`",
                [E("PROJECT", {"stage": "archived"}, "Harbour Lights (cancelled) is archived, not deleted")]),
 "M2 BR-001": ("APP (Plan step) + SCHEMA", "Edge Function drops unverified findings; `fk_precheck_finding_rule_code` → `legal_rule.rule_code`",
                [E("PRECHECK_RUN", {"attention_level": ("empty",)}, "every finding dropped: no level shown"),
                 E("PRECHECK_FINDING", {"rule_code": "A9-MIL"}, "a kept finding cites an approved rule")]),
 "M2 BR-002": ("SCHEMA", "`ck_legal_rule_approved_needs_signature`",
                [E("LEGAL_RULE", {"status": "draft"}, "draft rules without citation and approver (cannot be active)"),
                 E("LEGAL_RULE", {"status": "approved"}, "approved rules carry both")]),
 "M2 BR-003": ("NOT DATA", "wording rule of the result screens (SC-48, SC-27); tested by acceptance scenario M2 US-1",
                [E("PRECHECK_RUN", {"attention_level": "low"}, "a *Low* result must still not say *safe*")]),
 "M2 BR-004": ("SEED CHECK + APP", "seed_rules.attention_level() (M2 §9 thresholds) computes the level before writing",
                [E("PRECHECK_RUN", {"attention_level": "high"}, "2 *action* findings → High"),
                 E("PRECHECK_RUN", {"attention_level": "medium"}, "1 *action* finding → Medium"),
                 E("PRECHECK_RUN", {"country_guess": "US"}, "1 *notice* finding → Low (corrected 01/10/2026)")]),
 "M2 BR-005": ("VIEW (Plan step)", "view `v_dossier_check` counts slots in state `present` — no language model",
                [E("DOCUMENT_SLOT", {"project_id": FERRY, "doc_code": "A13_APPLICATION"}, "1 of 4 components present for The Last Ferry")]),
 "M2 BR-006": ("VIEW (Plan step)", "view `v_licensing_timeline` (shoot_date − buffer − 20 [− 20])",
                [E("PROJECT", {"project_name": "The Last Ferry"}, "15/03/2027, buffer 7 → 27/01/2027 and 16/02/2027"),
                 E("PROJECT", {"project_name": "Quiet Harbour Blues"}, "safe deadline already passed")]),
 "M2 BR-007": ("SCHEMA", "`fk_precheck_run_rule_version`, `fk_compliance_run_rule_version` (NOT NULL on compliance runs)",
                [E("COMPLIANCE_RUN", {"project_id": FERRY, "rule_version": "2026.07"}, "older run kept with its older version")]),
 "M2 BR-008": ("SCHEMA + SEED CHECK", "`ck_legal_rule_status`, `ck_legal_rule_active_matches_status`; no DELETE in any function",
                [E("LEGAL_RULE", {"status": "retired"}, "A9-MAP retired, not active, not deleted"),
                 E("AUDIT_LOG", {"action": "rule.retire"}, "the retirement is audited")]),
 "M3 BR-001": ("APP (Plan step)", "Edge Function returns attributes only; ranking in function `search_locations`",
                [E("LOCATION_QUERY", {"project_id": FERRY}, "the query stores extracted attributes, never a ranking")]),
 "M3 BR-002": ("VIEW (Plan step)", "function `search_locations` filters score ≥ 40 and ≥ 1 reason",
                [E("LOCATION", {"published": "true"}, "only published locations are scored")]),
 "M3 BR-003": ("APP (Plan step)", "scoring treats an empty field as *No data yet*",
                [E("LOCATION", {"slug": "cai-rang", "months_to_avoid": "[]"}, "no month to avoid recorded")]),
 "M3 BR-004": ("SCHEMA + SEED CHECK + TRIGGER (Plan step)", "`ck_location_published_matches_status`; seed_rules (contact verified); trigger `trg_location_publish_needs_contact`",
                [E("LOCATION", {"slug": "mui-ne"}, "contact not verified → awaiting_contact, not published"),
                 E("AUTHORITY_CONTACT", {"verified_at": ("lt", "2017")}, "contact verified in 2016 — older than the 12-month cycle")]),
 "M3 BR-005": ("RLS (Plan step)", "policy `rls_authority_contact_members`",
                [E("AUTHORITY_CONTACT", {"contact_email": ("nonempty",)}, "contacts with e-mail and phone that a guest must never receive")]),
 "M3 BR-006": ("SCHEMA", "`pk_province` (34 rows) + `merged_from`",
                [E("PROVINCE", {"slug": "ninh-binh"}, "Ninh Bình also answers to Hà Nam and Nam Định")]),
 "M3 BR-007": ("VIEW (Plan step)", "view `v_province_readiness` with sample sizes",
                [E("PROVINCE", {"slug": "hai-phong"}, "a province with no location: index shows *not enough data*")]),
 "M3 BR-008": ("SCHEMA + SEED CHECK", "`ck_location_intake_status`; seed_rules: an unpublished location is still shortlisted",
                [E("LOCATION", {"slug": "cua-van"}, "Cửa Vạn unpublished, never deleted"),
                 E("PROJECT_SHORTLIST", {"location_id": "@loc:cua-van"}, "still the backup of Quiet Harbour Blues")]),
 "M3 BR-009": ("SCHEMA", "LOCATION_QUERY has no user column; `project_id` optional",
                [E("LOCATION_QUERY", {"project_id": ("empty",)}, "guest queries with no project and no person")]),
 "M3 BR-010": ("SCHEMA + TRIGGER (Plan step)", "`ck_location_availability`; trigger `trg_location_availability_audit`",
                [E("LOCATION", {"availability": "paused"}, "Phong Nha paused, still published"),
                 E("AUDIT_LOG", {"action": "location.availability"}, "every change audited")]),
 "M4 BR-001": ("SCHEMA + RLS (Plan step)", "three tables `organisation`, `organisation_member_layer`, `organisation_private_layer`; policies `rls_org_member_layer_members`, `rls_org_private_after_nda`",
                [E("ORGANISATION_PRIVATE_LAYER", {}, "rate cards and direct contacts live in their own table")]),
 "M4 BR-002": ("SEED CHECK + APP", "seed_rules: every service group in the declared set of 12",
                [E("ORGANISATION", {"org_name": ("startswith", "Công ty Cổ phần")}, "boundary organisation with all 12 groups")]),
 "M4 BR-003": ("RLS (Plan step)", "partner accounts created by admin only (policy `rls_user_account_role_grant`)",
                [E("AUDIT_LOG", {"action": "role.grant"}, "Bến Xưa's account was granted by the admin")]),
 "M4 BR-004": ("SCHEMA + SEED CHECK", "`ck_organisation_badge_dates`; seed_rules: verified_until = verified_at + 12 months",
                [E("ORGANISATION", {"org_name": "Sông Hậu Film Services"}, "badge expired 15/08/2026")]),
 "M4 BR-005": ("SCHEMA + SEED CHECK", "`ck_collab_request_status`, `ck_collab_request_confirmed_at`",
                [E("COLLAB_REQUEST", {"status": "confirmed"}, "confirmed by the producer"),
                 E("COLLAB_REQUEST", {"status": "declined"}, "declined (final)"),
                 E("COLLAB_REQUEST", {"status": "withdrawn"}, "withdrawn (final)")]),
 "M4 BR-006": ("SEED CHECK + VIEW", "seed_rules: a slot is `present` only with an uploaded document",
                [E("DOCUMENT_SLOT", {"project_id": FERRY, "doc_code": "A13_SERVICE_AGREEMENT"}, "Bến Xưa accepted, agreement still *pending*")]),
 "M4 BR-007": ("TRIGGER (Plan step)", "trigger `trg_document_access_log_append_only` refuses UPDATE and DELETE",
                [E("DOCUMENT_ACCESS_LOG", {}, "5 view records, never edited")]),
 "M4 BR-008": ("SCHEMA + SEED CHECK", "`ck_organisation_org_status`; seed_rules: no open request to a deactivated organisation",
                [E("ORGANISATION", {"org_status": "deactivated"}, "Cửu Long Drone Works deactivated"),
                 E("COLLAB_REQUEST", {"org_id": "@org:Cửu Long Drone Works"}, "its request closed as withdrawn")]),
 "M4 BR-009": ("TRIGGER (Plan step)", "trigger `trg_collab_message_no_update`",
                [E("COLLAB_MESSAGE", {}, "messages of the Bến Xưa request thread")]),
 "M5 BR-001": ("NOT DATA", "the PDF renderer stamps every page (column `watermark` dropped, 04 minimality)",
                [E("BILINGUAL_DOCUMENT", {"pdf_url": ("nonempty",)}, "drafts with a PDF")]),
 "M5 BR-002": ("SEED CHECK + VIEW", "seed_rules: component b is `present` only when every paragraph is reviewed",
                [E("BILINGUAL_PARAGRAPH", {"project_id": FERRY, "status": "machine"}, "8 of 14 paragraphs not proofread"),
                 E("DOCUMENT_SLOT", {"project_id": FERRY, "doc_code": "A13_SCRIPT_VI"}, "so the script is *needs_fix*")]),
 "M5 BR-003": ("SCHEMA", "`ck_document_type_basis` (law, common, location)",
                [E("DOCUMENT_TYPE", {"basis": "location"}, "a location-specific document")]),
 "M5 BR-004": ("VIEW (Plan step)", "kit = `segment_requirement` + shortlisted locations",
                [E("DOCUMENT_SLOT", {"project_id": FERRY, "doc_code": "HERITAGE_SITE_PERMIT"}, "heritage consent added because Tràng An is shortlisted")]),
 "M5 BR-005": ("VIEW (Plan step)", "one view `v_licensing_timeline` used by M2, M5 and M0",
                [E("PROJECT", {"project_name": "The Last Ferry"}, "same dates on SC-12, SC-27, SC-29")]),
 "M5 BR-006": ("SCHEMA", "`pk_project_glossary` (project_id, term_en)",
                [E("PROJECT_GLOSSARY", {"term_en": "ferry"}, "ferry → đò, kept for every later draft")]),
 "M7 BR-001": ("SCHEMA + APP", "`reviewed_by` on PROVINCE_NOTICE; sending only from the VFDA domain",
                [E("PROVINCE_NOTICE", {"delivery_status": "sent"}, "sent after a VFDA review")]),
 "M7 BR-002": ("NOT DATA", "fixed sentence in the notice template",
                [E("PROVINCE_NOTICE", {"delivery_status": "sent"}, "every sent notice uses the template")]),
 "M7 BR-003": ("SCHEMA", "`ck_province_notice_response` (received, info_needed, cannot_support)",
                [E("PROVINCE_NOTICE", {"response": "cannot_support"}, "a *cannot support* reply")]),
 "M7 BR-004": ("VIEW (Plan step)", "`v_province_readiness` reads responded_at − sent_at",
                [E("PROVINCE_NOTICE", {"response": "received"}, "a reply with its time")]),
 "M7 BR-005": ("APP (Plan step)", "configuration flag *booking open* set by VFDA; no stored entity",
                [E("CONSULTATION_BOOKING", {}, "bookings exist only once VFDA has declared its hours")]),
 "M10 BR-001": ("SCHEMA + RLS (Plan step)", "`ck_moderation_item_content_status`; policy `rls_public_reads_approved_only`",
                [E("MODERATION_ITEM", {"content_status": "pending"}, "waiting: the public sees the last approved version")]),
 "M10 BR-002": ("SCHEMA", "`ck_moderation_item_hidden_needs_reason`",
                [E("MODERATION_ITEM", {"content_status": "hidden"}, "hidden with a reason")]),
 "M10 BR-003": ("SEED CHECK + VIEW", "seed_rules: indicators below 5 records carry no value; view `v_demand_index`",
                [E("QUARTERLY_REPORT", {}, "Q3 2026: indicators 4–6 below 5 records → *not enough data*")]),
 "M10 BR-004": ("SCHEMA", "`ck_quarterly_report_reread_before_export`",
                [E("QUARTERLY_REPORT", {"reread_by": ("nonempty",)}, "reread by Nguyễn Thị Thu Hà, then exported")]),
 "M10 BR-005": ("TRIGGER (Plan step)", "trigger `trg_audit_log_append_only`; the admin action and its record in one transaction",
                [E("AUDIT_LOG", {}, "14 records; none edited")]),
}

# Boundary rows: one per numeric or date rule of the module (C4)
BOUNDARIES = {
 "SYS": [("E-mail ≤ 254 characters (SYS §5.1 FR-001)", E("USER_ACCOUNT", {"email": ("len", 254)}, "e-mail of exactly 254 characters")),
         ("Full name ≤ 120 characters (SYS §5.1 FR-001)", E("PROFILE", {"full_name": ("len", 120)}, "name of exactly 120 characters")),
         ("Anonymised within 30 days (SYS BR-005)", E("USER_ACCOUNT", {"account_status": "deactivated"}, "deactivated and already anonymised"))],
 "M1": [("q2, q3 required only when q1 = true (M1 §5.1 FR-002)", E("SEGMENT_DECISION", {"q1_shoot_in_vn": "false", "q2_release": ("empty",)}, "q1 = false, no q2 / q3"))],
 "M0": [("Project name ≤ 200, logline ≤ 500 characters (M0 §5.1 FR-001)", E("PROJECT", {"project_name": ("len", 200)}, "200-character name, 500-character logline")),
        ("Buffer ≥ 0 days; days in Vietnam ≥ 0 (M2 BR-006)", E("PROJECT", {"buffer_days": "0"}, "buffer 0, 0 days, first day 31/12/2031")),
        ("Readiness 0–100 (M0 §5.1 FR-008)", E("READINESS_SNAPSHOT", {"readiness_total": "0.00"}, "0.00")),
        ("Readiness 0–100 (M0 §5.1 FR-008)", E("READINESS_SNAPSHOT", {"readiness_total": "100.00"}, "100.00"))],
 "M2": [("Deadline already passed (M2 BR-006)", E("PROJECT", {"project_name": "Quiet Harbour Blues"}, "first day 10/11/2026: safe deadline 24/09/2026 is past")),
        ("Quote starts at character 0 (M2 §6.1)", E("PRECHECK_FINDING", {"span_start": "0"}, "span starting at 0")),
        ("Rule title ≤ 200 characters (M2 §5.1 FR-002)", E("LEGAL_RULE", {"title_en": ("len", 200)}, "200-character title"))],
 "M3": [("Contact re-verified every 12 months (M3 BR-004)", E("AUTHORITY_CONTACT", {"verified_at": ("lt", "2017")}, "verified 04/01/2016")),
        ("Scene description 10–1000 characters (M3 §5.1 FR-010)", E("LOCATION_QUERY", {"scene_description": ("len", 1000)}, "1000 characters")),
        ("Scene description 10–1000 characters (M3 §5.1 FR-010)", E("LOCATION_QUERY", {"scene_description": ("len", 10)}, "10 characters")),
        ("Shooting month 1–12 (M3 §5.1 FR-007)", E("LOCATION_QUERY", {"shoot_month": "12"}, "month 12")),
        ("Coordinates inside Vietnam (ck_location_in_vietnam)", E("LOCATION", {"slug": "ca-mau-cape"}, "southernmost point, lat 8.615")),
        ("Name ≤ 200 characters (M3 §5.1 FR-002)", E("LOCATION", {"name_en": ("len", 200)}, "200-character name"))],
 "M4": [("Badge valid 12 months (M4 BR-004)", E("ORGANISATION", {"verified_until": "2026-08-15"}, "expired 15/08/2026")),
        ("At least 2 reference projects (M4 §5.1 FR-008)", E("VERIFICATION_REQUEST", {"status": "rejected"}, "1 reference → rejected with a reason")),
        ("Request note ≤ 1000 characters (M4 §5.1 FR-012)", E("COLLAB_REQUEST", {"note": ("len", 1000)}, "1000-character note")),
        ("Founded year (M4 §6.1)", E("ORGANISATION", {"founded_year": "1990"}, "founded 1990, all 34 provinces"))],
 "M5": [("Document versions from 1 (M5 §6.1)", E("DOCUMENT", {"version": "2"}, "version 2 replaces version 1, both kept")),
        ("Holiday far in the past (M5 §6.1)", E("PUBLIC_HOLIDAY", {"start_date": ("lt", "2024")}, "Tết 2023")),
        ("Expected, not yet official holiday (M5 §3 US-3)", E("PUBLIC_HOLIDAY", {"is_expected": "true"}, "expected dates"))],
 "M7": [("Unusual time zone (M7 §5.1 FR-005, IANA)", E("CONSULTATION_BOOKING", {"timezone": ("startswith", "America/Argentina")}, "America/Argentina/ComodRivadavia"))],
 "M10": [("Below 5 records → not enough data (M10 BR-003)", E("QUARTERLY_REPORT", {}, "indicator 5: 3 records, no value")),
         ("Period end ≥ start (ck_quarterly_report_period)", E("QUARTERLY_REPORT", {"period_end": "2026-09-30"}, "01/07–30/09/2026"))],
}

# Normalization exceptions kept on purpose: (entity, column, normal form broken, why kept, upkeep rule)
NF_EXCEPTIONS = [
 ("LEGAL_RULE", "is_active", "3NF (depends on status)", "read on every pre-check", "CHECK `ck_legal_rule_active_matches_status`"),
 ("LOCATION", "published", "3NF (depends on intake_status)", "M3 FR-005 output, read by every search", "CHECK `ck_location_published_matches_status`"),
 ("PROVINCE_NOTICE", "province_id", "3NF (derivable through the interest's location)", "records the province the notice was addressed to, even after a merger", "set once when drafted, never updated (M7 §6.1)"),
 ("PROVINCE_NOTICE", "authority_email, project_summary", "copies of AUTHORITY_CONTACT / PROJECT data", "what was actually sent must stay readable", "copied at send time, never updated (OQ-04-1, OQ-04-2 defaults)"),
 ("ORGANISATION", "verified_until", "3NF (verified_at + 12 months)", "read by every directory filter", "seed_rules check; set with verified_at in the same update"),
 ("BILINGUAL_DOCUMENT", "project_meta", "copy of PROJECT data", "the draft states the project as it was when drafted", "regenerated only when the member asks (OQ-04-5 default)"),
 ("READINESS_SNAPSHOT", "readiness_total", "derived value", "the nightly history cannot be recomputed later", "written once a night, never updated"),
 ("QUARTERLY_REPORT", "demand_index", "derived value", "a reread report must not change afterwards", "frozen at drafting time (M10 FR-007)"),
]
ARRAY_UPKEEP = "Kept as a JSON array (1NF exception): the whole list is what functions filter and show; every value is checked against its declared set by seed_rules.py and, at the Plan step, by the input validation (01 OQ 3)."

PRIVACY = [
 "No row describes a real person: every name is invented for this project (the persona list in `data/seed/README.md`).",
 "Every e-mail address is on an `example` domain (`*.example.*`, `anonymised.example`) — checked by `seed_rules.py`.",
 "Every phone number has the form `+84 000 000 1xx`, which cannot be a real Vietnamese number, and is used once — checked by `seed_rules.py`.",
 "No identity document, passport, tax or bank number is stored anywhere in the model.",
 "No real script is stored: pre-checks keep only a hash of the summary (M2 FR-007); synopsis texts in the seed are invented.",
 "Organisations, producer companies and projects are fictional; locations and provinces are real public places, described with mock text.",
 "Sensitive columns (authority contacts, partner private layer, project documents) are protected by Row Level Security (SYS BR-001) — listed in section 7.",
 "Nobody in the team knows of a real value in the seed files.",
]
